# Generated by Django 4.0.3 on 2022-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
