repos:

# format with black on commit
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

# format with isort on commit
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort

# autoflake
- repo: https://github.com/myint/autoflake
  rev: b330072a26bb13aea8843f8083cee5332d71f78f
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
        - --expand-star-imports
