version: '3'
services:
  test:
    image: snapshot-queries-py-${PYTHON_VERSION:-3.9}
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.9}
    volumes:
      - .:/python
    working_dir: /python/tests/test_django
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
